[package]
name = "dockernes"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = { version = "0.21", features = ["chrono"] }
pico-args = "0.5.0"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.4"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
thiserror = "2.0.20"
